### ISSUE TITLE
Failed to activate the auto-indent package

### ISSUE THREAD

**Issue by Globegitter** [griiin/atom-auto-indent#19]
[Enter steps to reproduce below:]

1. Update Atom to the latest version

**Atom Version**: 0.192.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [auto-indent](https://github.com/atom/auto-indent) package, v0.1.0

### Stack Trace

Failed to activate the auto-indent package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/Users/markus/.atom/packages/auto-indent/lib/auto-indent.coffee:8:32)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:222:19)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:203:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:147:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:195:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:434:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:418:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:298:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:413:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:394:46)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "tabs",
      "tree-view",
      "language-sass",
      "linter-eslint",
      "linter"
    ],
    "excludeVcsIgnoredPaths": false
  }
}
```

### Installed Packages

```coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
auto-indent, v0.1.0
better-handlebars, v0.1.1
color-picker, v1.6.0
editor-stats, v0.17.0
emmet, v2.3.7
es-navigation, v0.1.5
indent-guide-ext, v0.1.0
language-docker, v1.1.3
language-javascript-better, v1.3.0
language-json5, v1.1.0
sublime-tabs, v0.5.3

# Dev
No dev packages
```

**Comment by simonjosefsson** [comment]
This plugin currently have three deprecation warnings.
This means it will be crashing as above for _everyone_ when Atom goes 1.0

Click the orange warning icon in the lower right to see more information about these:

* The context menu CSON format has changed. Please see https://atom.io/docs/api/latest/ContextMenuManager#context-menu-cson-format for more info.
* Store package style sheets in the ```styles/``` directory instead of ```stylesheets/```
* Use activationCommands instead of activationEvents in your package.json

**Comment by simonjosefsson** [comment]
PR #18 should fix the undefined property issue

**Comment by griiin** [comment]
Should be fix now, sorry for the delay.
